# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dbv0038_diag import Dbv0038Diag

class TestDbv0038Diag(unittest.TestCase):
    """Dbv0038Diag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0038Diag:
        """Test Dbv0038Diag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0038Diag`
        """
        model = Dbv0038Diag()
        if include_optional:
            return Dbv0038Diag(
                meta = openapi_client.models.dbv0/0/38_meta.dbv0.0.38_meta(
                    plugin = openapi_client.models.dbv0_0_38_meta_plugin.dbv0_0_38_meta_plugin(
                        type = '', 
                        name = '', ), 
                    slurm = openapi_client.models.dbv0_0_38_meta_slurm.dbv0_0_38_meta_Slurm(
                        version = openapi_client.models.dbv0_0_38_meta_slurm_version.dbv0_0_38_meta_Slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', ), ),
                errors = [
                    openapi_client.models.dbv0/0/38_error.dbv0.0.38_error(
                        error_number = 56, 
                        error = '', 
                        source = '', 
                        description = '', )
                    ],
                statistics = openapi_client.models.dbv0_0_38_diag_statistics.dbv0_0_38_diag_statistics(
                    time_start = 56, 
                    rollups = [
                        openapi_client.models.dbv0_0_38_diag_statistics_rollups_inner.dbv0_0_38_diag_statistics_rollups_inner(
                            type = '', 
                            last_run = 56, 
                            last_cycle = 56, 
                            max_cycle = 56, 
                            total_time = 56, 
                            mean_cycles = 56, )
                        ], 
                    rpcs = [
                        openapi_client.models.dbv0_0_38_diag_statistics_rpcs_inner.dbv0_0_38_diag_statistics_RPCs_inner(
                            rpc = '', 
                            count = 56, 
                            time = openapi_client.models.dbv0_0_38_diag_statistics_rpcs_inner_time.dbv0_0_38_diag_statistics_RPCs_inner_time(
                                average = 56, 
                                total = 56, ), )
                        ], 
                    users = [
                        openapi_client.models.dbv0_0_38_diag_statistics_users_inner.dbv0_0_38_diag_statistics_users_inner(
                            user = '', 
                            count = 56, )
                        ], )
            )
        else:
            return Dbv0038Diag(
        )
        """

    def testDbv0038Diag(self):
        """Test Dbv0038Diag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
