# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dbv0038_job import Dbv0038Job

class TestDbv0038Job(unittest.TestCase):
    """Dbv0038Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0038Job:
        """Test Dbv0038Job
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0038Job`
        """
        model = Dbv0038Job()
        if include_optional:
            return Dbv0038Job(
                account = '',
                comment = openapi_client.models.dbv0_0_38_job_comment.dbv0_0_38_job_comment(
                    administrator = '', 
                    job = '', 
                    system = '', ),
                allocation_nodes = '',
                array = openapi_client.models.dbv0_0_38_job_array.dbv0_0_38_job_array(
                    job_id = 56, 
                    limits = openapi_client.models.dbv0_0_38_job_array_limits.dbv0_0_38_job_array_limits(
                        max = openapi_client.models.dbv0_0_38_job_array_limits_max.dbv0_0_38_job_array_limits_max(
                            running = openapi_client.models.dbv0_0_38_job_array_limits_max_running.dbv0_0_38_job_array_limits_max_running(
                                tasks = 56, ), ), ), 
                    task = '', 
                    task_id = 56, ),
                time = openapi_client.models.dbv0_0_38_job_time.dbv0_0_38_job_time(
                    elapsed = 56, 
                    eligible = 56, 
                    end = 56, 
                    start = 56, 
                    submission = 56, 
                    suspended = 56, 
                    system = openapi_client.models.dbv0_0_38_job_time_system.dbv0_0_38_job_time_system(
                        seconds = 56, 
                        microseconds = 56, ), 
                    total = openapi_client.models.dbv0_0_38_job_time_total.dbv0_0_38_job_time_total(
                        seconds = 56, 
                        microseconds = 56, ), 
                    user = openapi_client.models.dbv0_0_38_job_time_user.dbv0_0_38_job_time_user(
                        seconds = 56, 
                        microseconds = 56, ), 
                    limit = 56, ),
                association = openapi_client.models.dbv0/0/38_association_short_info.dbv0.0.38_association_short_info(
                    account = '', 
                    cluster = '', 
                    partition = '', 
                    user = '', ),
                cluster = '',
                constraints = '',
                derived_exit_code = openapi_client.models.dbv0/0/38_job_exit_code.dbv0.0.38_job_exit_code(
                    status = '', 
                    return_code = 56, 
                    signal = openapi_client.models.dbv0_0_38_job_exit_code_signal.dbv0_0_38_job_exit_code_signal(
                        signal_id = 56, 
                        name = '', ), ),
                exit_code = openapi_client.models.dbv0/0/38_job_exit_code.dbv0.0.38_job_exit_code(
                    status = '', 
                    return_code = 56, 
                    signal = openapi_client.models.dbv0_0_38_job_exit_code_signal.dbv0_0_38_job_exit_code_signal(
                        signal_id = 56, 
                        name = '', ), ),
                flags = [
                    ''
                    ],
                group = '',
                het = openapi_client.models.dbv0_0_38_job_het.dbv0_0_38_job_het(
                    job_id = 56, 
                    job_offset = 56, ),
                job_id = 56,
                name = '',
                mcs = openapi_client.models.dbv0_0_38_job_mcs.dbv0_0_38_job_mcs(
                    label = '', ),
                nodes = '',
                partition = '',
                priority = 56,
                qos = '',
                required = openapi_client.models.dbv0_0_38_job_required.dbv0_0_38_job_required(
                    cpus = 56, 
                    memory = 56, ),
                kill_request_user = '',
                reservation = openapi_client.models.dbv0_0_38_job_reservation.dbv0_0_38_job_reservation(
                    id = 56, 
                    name = 56, ),
                state = openapi_client.models.dbv0_0_38_job_state.dbv0_0_38_job_state(
                    current = '', 
                    reason = '', ),
                steps = [
                    openapi_client.models.dbv0/0/38_job_step.dbv0.0.38_job_step(
                        time = openapi_client.models.dbv0_0_38_job_step_time.dbv0_0_38_job_step_time(
                            elapsed = 56, 
                            end = 56, 
                            start = 56, 
                            suspended = 56, 
                            system = openapi_client.models.dbv0_0_38_job_time_system.dbv0_0_38_job_time_system(
                                seconds = 56, 
                                microseconds = 56, ), 
                            total = openapi_client.models.dbv0_0_38_job_time_total.dbv0_0_38_job_time_total(
                                seconds = 56, 
                                microseconds = 56, ), 
                            user = openapi_client.models.dbv0_0_38_job_time_user.dbv0_0_38_job_time_user(
                                seconds = 56, 
                                microseconds = 56, ), ), 
                        exit_code = openapi_client.models.dbv0/0/38_job_exit_code.dbv0.0.38_job_exit_code(
                            status = '', 
                            return_code = 56, 
                            signal = openapi_client.models.dbv0_0_38_job_exit_code_signal.dbv0_0_38_job_exit_code_signal(
                                signal_id = 56, 
                                name = '', ), ), 
                        nodes = openapi_client.models.dbv0_0_38_job_step_nodes.dbv0_0_38_job_step_nodes(
                            count = 56, 
                            range = '', ), 
                        tasks = openapi_client.models.dbv0_0_38_job_step_tasks.dbv0_0_38_job_step_tasks(
                            count = 56, ), 
                        pid = '', 
                        cpu = openapi_client.models.dbv0_0_38_job_step_cpu.dbv0_0_38_job_step_CPU(
                            requested_frequency = openapi_client.models.dbv0_0_38_job_step_cpu_requested_frequency.dbv0_0_38_job_step_CPU_requested_frequency(
                                min = 56, 
                                max = 56, ), 
                            governor = [
                                ''
                                ], ), 
                        kill_request_user = '', 
                        state = '', 
                        statistics = openapi_client.models.dbv0_0_38_job_step_statistics.dbv0_0_38_job_step_statistics(
                            energy = openapi_client.models.dbv0_0_38_job_step_statistics_energy.dbv0_0_38_job_step_statistics_energy(
                                consumed = 56, ), ), 
                        step = openapi_client.models.dbv0_0_38_job_step_step.dbv0_0_38_job_step_step(
                            job_id = 56, 
                            het = openapi_client.models.dbv0_0_38_job_step_step_het.dbv0_0_38_job_step_step_het(
                                component = 56, ), 
                            id = '', 
                            name = '', ), 
                        task = '', 
                        tres = openapi_client.models.dbv0_0_38_job_step_tres.dbv0_0_38_job_step_tres(
                            requested = openapi_client.models.dbv0_0_38_job_step_tres_requested.dbv0_0_38_job_step_tres_requested(
                                average = [
                                    openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                                        type = '', 
                                        name = '', 
                                        id = 56, 
                                        count = 56, )
                                    ], 
                                max = [
                                    openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                                        type = '', 
                                        name = '', 
                                        id = 56, 
                                        count = 56, )
                                    ], 
                                min = , ), 
                            consumed = openapi_client.models.dbv0_0_38_job_step_tres_requested.dbv0_0_38_job_step_tres_requested(), 
                            allocated = , ), )
                    ],
                tres = openapi_client.models.dbv0_0_38_job_tres.dbv0_0_38_job_tres(
                    allocated = [
                        openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    requested = [
                        openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], ),
                user = '',
                wckey = openapi_client.models.dbv0_0_38_job_wckey.dbv0_0_38_job_wckey(
                    flags = [
                        ''
                        ], ),
                working_directory = '',
                container = ''
            )
        else:
            return Dbv0038Job(
        )
        """

    def testDbv0038Job(self):
        """Test Dbv0038Job"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
