# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.openapi_api import OpenapiApi


class TestOpenapiApi(unittest.TestCase):
    """OpenapiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenapiApi()

    def tearDown(self) -> None:
        pass

    def test_openapi(self) -> None:
        """Test case for openapi

        Retrieve OpenAPI Specification
        """
        pass

    def test_openapi_v3_get(self) -> None:
        """Test case for openapi_v3_get

        Retrieve OpenAPI Specification
        """
        pass

    def test_openapijson(self) -> None:
        """Test case for openapijson

        Retrieve OpenAPI Specification
        """
        pass

    def test_openapiyaml(self) -> None:
        """Test case for openapiyaml

        Retrieve OpenAPI Specification
        """
        pass


if __name__ == '__main__':
    unittest.main()
