# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0040_step_nodes import V0040StepNodes

class TestV0040StepNodes(unittest.TestCase):
    """V0040StepNodes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0040StepNodes:
        """Test V0040StepNodes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0040StepNodes`
        """
        model = V0040StepNodes()
        if include_optional:
            return V0040StepNodes(
                count = 56,
                range = '',
                list = [
                    ''
                    ]
            )
        else:
            return V0040StepNodes(
        )
        """

    def testV0040StepNodes(self):
        """Test V0040StepNodes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
