site_name: SLURM-CLI-API-Proxy-client
site_description: Command Line Interface (CLI) proxy for SLURM REST API
strict: true
site_url: https://github.com/SLURM-CLI-API-Proxy/SLURM-CLI-API-Proxy-client

theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light blue
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: light blue
    accent: indigo
    toggle:
      icon: material/weather-night
      name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
  icon:
    logo: 'material/library-outline'
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: 'favicon.png'

repo_name: SLURM-CLI-API-Proxy/SLURM-CLI-API-Proxy-client
repo_url: https://github.com/SLURM-CLI-API-Proxy/SLURM-CLI-API-Proxy-client
edit_uri: edit/dev/docs/

# https://www.mkdocs.org/user-guide/configuration/#validation
#validation:
#  omitted_files: warn
#  absolute_links: warn
#  unrecognized_links: warn

nav:
- Developer documentation:
  - Introduction: index.md
  - Setup: setup.md
  - Limitations: limitations.md  
  - Developer guide: design.md
  

markdown_extensions:
# https://python-markdown.github.io/extensions/
- toc:
    permalink: true
- admonition
# https://facelessuser.github.io/pymdown-extensions
- pymdownx.details
- pymdownx.snippets:
    check_paths: true
    base_path: [docs/reference_code_snippets, "."]
- pymdownx.highlight:
    anchor_linenums: true
    pygments_lang_class: true
- pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.magiclink

watch:
- docs

plugins:
- search