# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0038_signal import V0038Signal

class TestV0038Signal(unittest.TestCase):
    """V0038Signal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV0038Signal(self):
        """Test V0038Signal"""
        # inst = V0038Signal()

if __name__ == '__main__':
    unittest.main()
