# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dbv0038_update_account import Dbv0038UpdateAccount

class TestDbv0038UpdateAccount(unittest.TestCase):
    """Dbv0038UpdateAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0038UpdateAccount:
        """Test Dbv0038UpdateAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0038UpdateAccount`
        """
        model = Dbv0038UpdateAccount()
        if include_optional:
            return Dbv0038UpdateAccount(
                accounts = [
                    openapi_client.models.dbv0/0/38_account.dbv0.0.38_account(
                        associations = [
                            openapi_client.models.dbv0/0/38_association_short_info.dbv0.0.38_association_short_info(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', )
                            ], 
                        coordinators = [
                            openapi_client.models.dbv0/0/38_coordinator_info.dbv0.0.38_coordinator_info(
                                name = '', 
                                direct = 56, )
                            ], 
                        description = '', 
                        name = '', 
                        organization = '', 
                        flags = [
                            ''
                            ], )
                    ]
            )
        else:
            return Dbv0038UpdateAccount(
        )
        """

    def testDbv0038UpdateAccount(self):
        """Test Dbv0038UpdateAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
