# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dbv0038_association_max import Dbv0038AssociationMax

class TestDbv0038AssociationMax(unittest.TestCase):
    """Dbv0038AssociationMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0038AssociationMax:
        """Test Dbv0038AssociationMax
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0038AssociationMax`
        """
        model = Dbv0038AssociationMax()
        if include_optional:
            return Dbv0038AssociationMax(
                jobs = openapi_client.models.dbv0_0_38_association_max_jobs.dbv0_0_38_association_max_jobs(
                    per = openapi_client.models.dbv0_0_38_association_max_jobs_per.dbv0_0_38_association_max_jobs_per(
                        wall_clock = 56, ), ),
                per = openapi_client.models.dbv0_0_38_association_max_per.dbv0_0_38_association_max_per(
                    account = openapi_client.models.dbv0_0_38_association_max_per_account.dbv0_0_38_association_max_per_account(
                        wall_clock = 56, ), ),
                tres = openapi_client.models.dbv0_0_38_association_max_tres.dbv0_0_38_association_max_tres(
                    per = openapi_client.models.dbv0_0_38_association_max_tres_per.dbv0_0_38_association_max_tres_per(
                        job = [
                            openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        node = [
                            openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], ), 
                    total = , 
                    minutes = openapi_client.models.dbv0_0_38_association_max_tres_minutes.dbv0_0_38_association_max_tres_minutes(
                        total = , ), )
            )
        else:
            return Dbv0038AssociationMax(
        )
        """

    def testDbv0038AssociationMax(self):
        """Test Dbv0038AssociationMax"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
