# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dbv0038_qos_limits import Dbv0038QosLimits

class TestDbv0038QosLimits(unittest.TestCase):
    """Dbv0038QosLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0038QosLimits:
        """Test Dbv0038QosLimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0038QosLimits`
        """
        model = Dbv0038QosLimits()
        if include_optional:
            return Dbv0038QosLimits(
                factor = 1.337,
                max = openapi_client.models.dbv0_0_38_qos_limits_max.dbv0_0_38_qos_limits_max(
                    wall_clock = openapi_client.models.dbv0_0_38_qos_limits_max_wall_clock.dbv0_0_38_qos_limits_max_wall_clock(
                        per = openapi_client.models.dbv0_0_38_qos_limits_max_wall_clock_per.dbv0_0_38_qos_limits_max_wall_clock_per(
                            qos = 56, 
                            job = 56, ), ), 
                    jobs = openapi_client.models.dbv0_0_38_qos_limits_max_jobs.dbv0_0_38_qos_limits_max_jobs(
                        active_jobs = openapi_client.models.dbv0_0_38_qos_limits_max_jobs_active_jobs.dbv0_0_38_qos_limits_max_jobs_active_jobs(), ), 
                    accruing = openapi_client.models.dbv0_0_38_qos_limits_max_accruing.dbv0_0_38_qos_limits_max_accruing(), 
                    tres = openapi_client.models.dbv0_0_38_qos_limits_max_tres.dbv0_0_38_qos_limits_max_tres(
                        minutes = openapi_client.models.dbv0_0_38_qos_limits_max_tres_minutes.dbv0_0_38_qos_limits_max_tres_minutes(), ), ),
                min = openapi_client.models.dbv0_0_38_qos_limits_min.dbv0_0_38_qos_limits_min(
                    priority_threshold = 56, 
                    tres = openapi_client.models.dbv0_0_38_qos_limits_min_tres.dbv0_0_38_qos_limits_min_tres(
                        per = openapi_client.models.dbv0_0_38_qos_limits_min_tres_per.dbv0_0_38_qos_limits_min_tres_per(
                            job = [
                                openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                                    type = '', 
                                    name = '', 
                                    id = 56, 
                                    count = 56, )
                                ], ), ), )
            )
        else:
            return Dbv0038QosLimits(
        )
        """

    def testDbv0038QosLimits(self):
        """Test Dbv0038QosLimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
