# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm DB.

    The version of the OpenAPI document: Slurm-23.11.4&openapi/dbv0.0.38&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmctld&openapi/v0.0.38&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dbv0038_qos_limits_min_tres import Dbv0038QosLimitsMinTres

class TestDbv0038QosLimitsMinTres(unittest.TestCase):
    """Dbv0038QosLimitsMinTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0038QosLimitsMinTres:
        """Test Dbv0038QosLimitsMinTres
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0038QosLimitsMinTres`
        """
        model = Dbv0038QosLimitsMinTres()
        if include_optional:
            return Dbv0038QosLimitsMinTres(
                per = openapi_client.models.dbv0_0_38_qos_limits_min_tres_per.dbv0_0_38_qos_limits_min_tres_per(
                    job = [
                        openapi_client.models.dbv0_0_38_tres_list_inner.dbv0_0_38_tres_list_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], )
            )
        else:
            return Dbv0038QosLimitsMinTres(
        )
        """

    def testDbv0038QosLimitsMinTres(self):
        """Test Dbv0038QosLimitsMinTres"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
